### ISSUE TITLE
weston-git: sources not found when cloning via https

### ISSUE THREAD

**Issue by AladW** [Earnestly/pkgbuilds#1]
```
 % makepkg -sr                
==> Making package: weston-git 1.10.0.r55.gc6459c49-1 (So 20. Mär 13:54:33 CET 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning weston git repo...
Cloning into bare repository '/home/sources/weston'...
fatal: repository 'https://anongit.freedesktop.org/wayland/weston/' not found
==> ERROR: Failure while downloading weston git repo
    Aborting...
```

I've noticed this with other freedesktop repos too (`wayland-git`, though `wlc-git` and `libinput-git` are fine), apparently only git:// and http:// work in some cases.

**Comment by Earnestly** [comment]
Ah, no it does work but the url is slightly incorrect since I naively just prepended `git+https` instead of also updating the url.

Fixed: https://github.com/Earnestly/pkgbuilds/commit/cbccf36853827628322c0be6fe422dbda874e223
