### ISSUE TITLE
weechat-git: missing install file

### ISSUE THREAD

**Issue by AladW** [Earnestly/pkgbuilds#2]
A reference to an install file was added with d6ecbca333deb441667e81319033e3f8153fa727, though weechat-git.install isn't present in the repo.

**Comment by Earnestly** [comment]
Fixed: https://github.com/Earnestly/pkgbuilds/commit/10d14d5df1dca0c0295efbe5dc9935c154f31657

Hopefully hooks will come sooner rather than later.
